travis:
  secure:
    BINSTAR_TOKEN: dt1mgXyASThispt+3cA4kx8nChgeLSVeLmI944uVjW78Fq+ja76+nYtZH4zsplWkzDpq+a6Xa2v8yojsNtSrom00fcS147UYOi+QWOAaD3Q3HvcLRISx9LVEXIAUIiPg9Q8oe8GpnTzBtkNZ+L5UcUmd5F6htOC7erP6gQVuWc4MRhMHuRs0GWwuuAPHGosYszKMRpEKM+1dMkliLnaPAJMOpku8ReF/ChWCKRjxCJSWAi+EL/Rj0F+CyUvZwEA1KVl+pkKyiEbc7/uAVliWhY0Soj9f88eFPeq/aSQp9iZGVBai0J0b9rfNhRo/Yu6fzsH3wojQXaxnJAVckkqNecdE6MIRq3yWdy/wrKYsLXmbO1v3NDb+NjsvN9L5u/kLy5Is01AlhU2xHciETWbZuFtp4UewtzqbIzQ4Sy/2AMpDJuXnRLZBS3VFBbB6hmIVsA340Hl1SRpwtps5l02DSLVImvrAy/Lbus4A5HwFrKlaSgWRQ/BfrLGI+SYZ6bztbMNiOhX/hrpw+7qcoxt44deixhEpelmSsPLIMMCr7LM0bIeBxfxPEJGpKlUC4NJl+4kQQJPZT/+7F+8I0wKsnC2b1QmYv+0m2bx5VK2c07gC1WwXHUs78KxPJfdiNK/J/npH9IH34RAyC9fMMyn0GTtNdG6QBF/dWbtRX6y44g4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
