travis:
  secure:
    BINSTAR_TOKEN: H2okjfvUdmmGc8KwsvB74G606bNFytvv9HMKltDcMfB++FyLVP5/02UpwEgN1/66UbGNNoG9K0erZ9pWgxd1vVDh2opx6bTl/dblyGZLTLvYpZu6nAo2rMHL9AUBTbuay/18fJuz37y0RaLlXiIErjjveQXC0BD1EfKsBppSHbMqOOrZAkVX4qQmHRat7RTRDV6/4uyrJXtNCE8g48QycJBowVUHdPtue15EUFPknxwgR5gBsjFOhQT5xT0LPpoTwoMxWgx5Cd2iDJkvcSD1o6pkQW5zoMcMza+vIEeCqFsn4BvjYVjoRhSn+A5ubdkX7ubxnPiSWku1psOhMw5OQK0Gldb0EiTHsq7K8y9YcQIPVW8CCJzvENS0XjgDpmGWhgXYSW0EFWaCya/u3e8u0QJbjPG3gSVH6YDZ6Zb/1+wXiUAIEz5lH3uKKeKr8EGhqE8iijHNEp3xrtZ+RQAWjdZYFmwksRmZ74V5QU7NnAFcb7WN9hB+XLJa+PlPEwp9FL4Uxv2X3zy+WJTolqMl5Lv170+dCZBWcjROZfhuiiBDw06KkqWYnB0s3VAWx1WsI7Lh9RypOC9c86ez1bBnESlIHgDa0mgwrp9Q4DAff+2frN9w+4c3camtg+7yQyyL/bpF523+6IO1hI6EaSxq6Nvl6LqGdfME3a6U0PrZv70=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
